### ISSUE TITLE
Task Saving Feature

### ISSUE THREAD

**Issue by bitscurrent** [chingu-voyages/v47-tier2-team-11#19]
**__Feature Description__**

- [x]  Implement local storage functionality post-initial checklist generation.
- [x]  Store the generated checklist in the local storage to persist user data beyond the initial session.
- [x]  Introduce a "**Save**" button specifically for updating local storage.
- [x]  Store generated checklists in local storage to persist user data beyond the initial session.

Ensure saving to local storage occurs on each change.

**__Major User Stories/tasks__**
- [ ] #20 
- [ ] Update the checklist in the local storage whenever changes are made.
